vector_db:
  index_name: "langchain-text-index"

embedding_model:
  provider: "OpenAI"
  model_name: "text-embedding-3-large"

llm:
  openai:
    provider: "OpenAI"
    model_name: "gpt-4o"

retriver:
  top_k: 3
  score_threshold: 0.5

tools:
  tavily:
    max_results: 5